import { type NextPage } from "next";
import Head from "next/head";
import MetaTag from "~/components/common/meta.common";

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <MetaTag title="Contact Us - Shalom Plaques" />
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="icons/favicon.png" />
      </Head>
      <div>Content</div>
    </>
  );
};

export default Contact;
