import Head from 'next/head';
import Image from 'next/image';
import Carousel from '../components/Carousel';
import Header from '../components/Header';
import Hero from '../components/Hero';

export default function Home() {
	return (
		<div className="relative">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className="mt-head overflow-hidden h-fit">
				<Hero />
				<Carousel />
			</div>
		</div>
	);
}
