export const imgString = [
  "machine-1.JPG",
  "machine-2.JPG",
  "working-1.JPG",
  "working-2.JPG",
  "working-3.JPG",
  "working-4.JPG",
  "working-5.JPG",
  "working-6.JPG",
  "working-7.JPG",
];

export const countries = [
  { code: "US", label: "United States" },
  { code: "CA", label: "Canada" },
  { code: "GB", label: "Great Britain" },
  { code: "DE", label: "Germany" },
  { code: "NL", label: "Netherlands" },
  { code: "RO", label: "Romania" },
  { code: "KR", label: "South Korea" },
  { code: "JP", label: "Japan" },
  { code: "TW", label: "Taiwan" },
  { code: "HK", label: "Hong Kong" },
  { code: "SG", label: "Singapore" },
  { code: "AE", label: "United Arab Emirates" },
  { code: "LB", label: "Lebanon" },
  { code: "KW", label: "Kuwait" },
  { code: "OM", label: "Oman" },
  { code: "BH", label: "Bahrain" },
  { code: "QA", label: "Qatar" },
  { code: "EG", label: "Egypt" },
  { code: "IN", label: "India" },
  { code: "AU", label: "Australia" },
  { code: "NZ", label: "New Zealand" },
  { code: "ID", label: "Indonesia" },
  { code: "FJ", label: "Fiji" },
];

export const sampleCategories = [
  "Box",
  "Church Supplies",
  "Cross",
  "Magnets",
  "Ornaments",
  "Wall Plaques",
  "Photo Frame",
  "Knock Down Products",
  "Table Plaques",
  "Keyring",
  "Medium Density Fibreboard",
];
